name: API Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run API Tests
        run: |
          newman run collections/reqres_api_tests.postman_collection.json \
          -e environments/reqres_env.postman_environment.json \
          --reporters cli,html \
          --reporter-html-export reports/newman_report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: API Test Report
          path: reports/newman_report.html
